version: '3'
services:

  score-service:
    image: apatrios/score-service:0.0.2
    ports:
      - "8082:8082"
    environment:
      APP_PORT: 8082
      DATASOURCE_URL: jdbc:postgresql://db/postgres?createDatabaseIfNotExists=true
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: password
      JWT_SECRET: 4A614E645267556B58703273357638792F423F4528482B4D6250655368566D59
    depends_on:
      - db
    command: bash -c "/apps/wait-for-service.sh db 5432 && /apps/entrypoint.sh"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
#
#    image: mysql:8.0.23
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#    ports:
#      - 3306:3306
#    volumes:
#      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: